### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by L-iot** [0x27/CiscoRV320Dump#6]
Hello, I started playing around with your CiscoRV320dump tool when i got the following errors in kali linux 4.18.20-2kali2 (2018-11-30) x86_64 GNU/Linux as well as in Linux kali 4.19.0-kali-amd64 #1 SMP Debian 4.19.13-lkali (2019-01-03) x86_64 GNU/Linux:

{+} Sending request to https://x.x.x.x:8433/cgi-bin/config.exp
{!} Exception while sending request, printing...
HTTPSConnectionPool (host='x.x.x.x' , port=8443) : Max retries exceeded with url: /cgi-bin/config.exp (Caused by SSLError ("bad Handshake: SysCallError(-1, 'Unexpected EOF')",),))

{+} Sending request to https://x.x.x.x:8433/cgi-bin/export_debug_msg.exp
{!} Exception while sending request, printing...
HTTPSConnectionPool (host='x.x.x.x' , port=8443) : Max retries exceeded with url: /cgi-bin/config.exp (Caused by SSLError ("bad Handshake: SysCallError(-1, 'Unexpected EOF')",),))

 can you point me in the right direction to find a sollution for that error?

**Comment by 0x27** [comment]
Looks like the SSL server on the remote end is not working properly. 

Can you try something like this? `curl -vvk https://x.x.x.x:8443/cgi-bin/config.exp`

**Comment by L-iot** [comment]
:~@#curl -vvk https://xxx.xxx.xxx.xxx/cgi-bin/config.exp
*Expire in 0 ms for 6 (transfer xxxxxxxxxxxxxx)
* Trying xxx.xxx.xxx.xxx...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer xxxxxxxxxxxxxx)
* Connected to xxx.xxx.xxx.xxx (xxx.xxx.xxx.xxx) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile:none
 CApath:  /etc/ssl/certs
*TLSv1.3 (OUT) , TLS handshake, Client hello (1) : 
*OpenSSL_connect: SSL_ERROR_SYSCALL in connection to xxx.xxx.xxx.xxx:8443
*Closing connection 0
curl:  (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to xxx.xxx.xxx.xxx:8443

**Comment by L-iot** [comment]
It seems that the error is due to the fact, that the router uses a selfsigned cert. When i manually confirm the security exception and then enter https://xxx.xxx.xxx.xxx/cgi-bin/config.exp the configuration file is dowloaded. 

manual usage of the /cgi-bin/export_debug_msg.exp throws 2 different error messages , even when the first call worked.(cgi-bin/config.exp)

the errors are:

Error: The page you are trying to access is not available. Click here to go back. (which might indicate a patched firmware)

and

Critical failure. Please contact support.
